### PR TITLE
(feat) Implement PUT rep and other small fixes

### LINKED ISSUE #33: (feat) Initiate request handler for POST Rep

### PR DESCRIPTION
**Pull request by mkeith121**
Closes #33, #42, #45

### CODE REVIEW

File: server/db/userSchema.js [hunk 1]
```diff
@@ -2,8 +2,11 @@ var mongoose = require('mongoose');
...
 
 var userSchema = new Schema({
-  name: { type: String, required: true },
-  location: { type: String, required: false }
+  firstName: { type: String, required: true },
+  lastName: { type: String, required: false },
+  email: { type: String, required: true },
+  location: { type: String, required: false },
+  projects: { type: Array, required: false }
 }, { timestamps: true });
```
Comment (tmpace) [inline server/db/userSchema.js:11]: Should we have a password field here?
